# Original under MIT License: https://gitlab.com/pages/hugo/blob/master/LICENSE
# All available Hugo versions are listed here: https://gitlab.com/pages/hugo/container_registry
# Modifications:
# - Hugo "Extended" image
# - Cloudflare cache purging via stage
image: registry.gitlab.com/pages/hugo/hugo_extended:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build

pages:
  stage: build
  script:
    - hugo version
    - hugo
    #- "find public/amp/ -name *.jpg -exec rm '{}' \\;"
    - "apk add curl && curl -X POST \"https://api.cloudflare.com/client/v4/zones/$CLOUDFLARE_ZONE/purge_cache\" -H \"Authorization: Bearer $CLOUDFLARE_API_KEY\" -H \"Content-Type: application/json\" --data '{\"purge_everything\":true}' || echo 'WARN: FAILED TO PURGE CACHE'"
  artifacts:
    paths:
      - public
  only:
    refs:
      - main
    changes:
      - "!README.md"